#define DLG_MAIN                 32
#define TXT_FILE                 100
#define LB_FILE                  101
#define EF_FILE                  102
#define BTN_FIND                 103
#define BTN_ADD0                 104
#define BTN_REM0                 105
#define BTN_REMALL               106
#define CHK_RECUR                107
#define TXT_STRINGS              108
#define LB_STRINGS               109
#define TXT_FIND                 110
#define EF_STRFIND               111
#define TXT_REPLACE              112
#define EF_STRREPL               113
#define BTN_ADD1                 114
#define BTN_REM1                 115
#define CHK_NOCASE               116
#define CHK_ESCAPE               117
#define BTN_START                118
#define BTN_EXIT                 119
#define BTN_MOVEUP               120
#define BTN_MOVEDOWN             121

